### ISSUE TITLE
Rotating the Sky?

### ISSUE THREAD

**Issue by samedayjeremy** [loginov-rocks/three-sky#1]
Is there a way to rotate the Sky created using this package?  Adjusting the rotation on the Sky object does not seem to effect the horizon/lighting effects.

My scene's camera uses `camera.up.set(0, 0, 1);` to make the Z axis vertical. 

I'm having trouble finding a way to rotate the sky to match.

![screen shot 2019-01-18 at 5 31 00 pm](https://user-images.githubusercontent.com/447535/51416310-e4b15b80-1b46-11e9-9c51-b430dd032f4e.png)
This zoomed out image shows the rotated sphere (big axes lines) vs the scene axes lines.  This method isn't working. I need to rotate the horizon 90* around the X axis

**Comment by loginov-rocks** [comment]
Hi @jeremylach ! Thanks for reporting, I believe that should go to the [Sky.js](https://github.com/mrdoob/three.js/blob/master/examples/js/objects/Sky.js) contributors.
